# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('trigger_text', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_question_set', to='intelicopter.Question')),
                ('trigger_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_question_set', to='intelicopter.Question')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelicopter.Question'),
        ),
    ]
