# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelicopter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='trigger_range',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
