# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelicopter', '0002_trigger_trigger_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=None, null=True)),
                ('question_number', models.IntegerField(default=None, null=True)),
                ('answer', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
