# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intelicopter', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
